parameters:
#    vax_front.example.class: Vax\FrontBundle\Example

services:
#    vax_front.example:
#        class: %vax_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
